default: &default
  secret_key_base: <%= ENV['secret_key_base'] %>
  database_name: <%= ENV['database_name'] %>
  database_username: <%= ENV['database_username'] %>
  database_password: <%= ENV['database_password'] %>
  database_host: <%= ENV['database_host'] %>
  database_port: <%= ENV['database_port'] %>
  honeybadger_api_key: <%= ENV['honeybadger_api_key'] %>
  jwt_secret: <%= ENV['jwt_secret'] %>

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
